export const MESSAGES_STRINGS = {
  en: {
    EMAIL: "Email",
    PASSWORD: "Password",

    LOGIN_TITLE: "Welcome back",
    LOGIN_SUBTITLE: "Sign in to continue",
    LOGIN_EMAIL_PLACEHOLDER: "Email",
    LOGIN_PASSWORD_PLACEHOLDER: "Password",
    LOGIN_REMEMBER_ME: "Remember me",
    LOGIN_SUBMIT: "Log In",
    LOGIN_TO_REGISTER: "You don't have an account? Register here.",
    LOGIN_MISSING_INFO_TITLE: "Missing information",
    LOGIN_MISSING_INFO_MESSAGE: "Enter email and password.",
    LOGIN_INVALID_EMAIL_TITLE: "Invalid email",
    LOGIN_INVALID_EMAIL_MESSAGE: "Enter email in the format example@email.com.",
    LOGIN_INVALID_PASSWORD_TITLE: "Invalid password",
    LOGIN_INVALID_PASSWORD_MESSAGE: "Password must be at least 6 characters long.",
    LOGIN_FAILED_TITLE: "Login failed",
    LOGIN_FAILED_MESSAGE: "Try again.",

    REGISTER_TITLE: "Create account",
    REGISTER_SUBTITLE: "Sign up to start writing notes",
    REGISTER_EMAIL_PLACEHOLDER: "Email",
    REGISTER_PASSWORD_PLACEHOLDER: "Password",
    REGISTER_SUBMIT: "Register",
    REGISTER_TO_LOGIN: "If you have an account? Login here.",
    REGISTER_MISSING_INFO_TITLE: "Missing information",
    REGISTER_MISSING_INFO_MESSAGE: "Enter email and password.",
    REGISTER_INVALID_EMAIL_TITLE: "Invalid email",
    REGISTER_INVALID_EMAIL_MESSAGE: "Enter email in the format example@email.com.",
    REGISTER_INVALID_PASSWORD_TITLE: "Invalid password",
    REGISTER_INVALID_PASSWORD_MESSAGE: "Password must be at least 6 characters long.",
    REGISTER_SUCCESS_TITLE: "Success",
    REGISTER_SUCCESS_MESSAGE: "Account has been created successfully.",
    REGISTER_FAILED_TITLE: "Registration failed",

    AUTH_INVALID_EMAIL: "Invalid email address.",
    AUTH_INVALID_CREDENTIALS: "Invalid email or password.",
    AUTH_TOO_MANY_REQUESTS: "Too many attempts. Try again in a few minutes.",
    AUTH_NETWORK_FAILED: "No internet connection. Check your network and try again.",
    AUTH_LOGIN_DEFAULT: "Login failed. Try again.",
    AUTH_EMAIL_IN_USE: "This email is already registered.",
    AUTH_WEAK_PASSWORD: "Password is too weak. Use at least 6 characters.",
    AUTH_REGISTER_DEFAULT: "Registration failed. Try again.",

    NOTE_EDIT_TITLE: "Edit note",
    NOTE_CREATE_TITLE: "Create note",
    NOTE_TITLE_LABEL: "Title",
    NOTE_TITLE_PLACEHOLDER: "Title",
    NOTE_CONTENT_LABEL: "Content",
    NOTE_CONTENT_PLACEHOLDER: "Write your note...",
    NOTE_TAGS_LABEL: "Tags",
    NOTE_TAGS_PLACEHOLDER: "project, exam, homework",
    NOTE_PIN_LABEL: "Pin to top",
    NOTE_COLOR_LABEL: "Color",
    NOTE_REMINDER_LABEL: "Reminder",
    NOTE_UPDATE_BUTTON: "Update note",
    NOTE_SAVE_BUTTON: "Save note",
    NOTE_NOT_FOUND_TITLE: "Note not found",
    NOTE_NOT_FOUND_MESSAGE: "Unable to load the requested note.",
    NOTE_LOAD_FAILED_TITLE: "Error",
    NOTE_LOAD_FAILED_MESSAGE: "Unable to load the note. Try again.",
    NOTE_MISSING_INFO_TITLE: "Missing information",
    NOTE_MISSING_INFO_MESSAGE: "Title and content are required.",
    NOTE_INVALID_TITLE_TITLE: "Invalid title",
    NOTE_INVALID_TITLE_SHORT: "Title must be at least 3 characters.",
    NOTE_INVALID_TITLE_LONG: "Title can have a maximum of 120 characters.",
    NOTE_INVALID_CONTENT_TITLE: "Invalid content",
    NOTE_INVALID_CONTENT_SHORT: "Content must be at least 5 characters.",
    NOTE_INVALID_CONTENT_LONG: "Content can have a maximum of 5000 characters.",
    NOTE_NOT_SIGNED_IN_TITLE: "Not signed in",
    NOTE_NOT_SIGNED_IN_MESSAGE: "Sign in to save the note.",
    NOTE_SAVE_FAILED_TITLE: "Error",
    NOTE_SAVE_FAILED_MESSAGE: "Unable to save the note. Try again.",
    NOTE_REMINDER_PREVIEW: (dateText) => `Will remind on ${dateText}`,

    HOME_GREETING: (email) => `Hey, ${email}`,
    HOME_SEARCH_PLACEHOLDER: "Search notes",
    HOME_NEW_NOTE_BUTTON: "+ New note",
    HOME_STATS_TOTAL: "Your notes",
    HOME_STATS_PINNED: "Pinned",
    HOME_LIST_EMPTY: "No notes yet. Start by creating one!",
    HOME_LIST_CREATE_BUTTON: "Create note",
    HOME_NOTE_DRAFT: "Draft",
    HOME_NOTE_UNPIN: "Unpin",
    HOME_NOTE_PIN: "Pin",
    HOME_NOTE_EDIT: "Edit",
    HOME_NOTE_DELETE: "Delete",
    HOME_FILTER_ALL: "All",
    HOME_FILTER_PINNED: "Pinned",
    HOME_FILTER_RECENT: "Recent",
    HOME_SORT_RECENT: "Recent",
    HOME_SORT_TITLE: "A-Z",
    HOME_FILTER_COLOR: "Color",
    HOME_TAB_TITLE: "Home",
    CREATE_TAB_TITLE: "Create",
    LOGOUT_TAB_TITLE: "Logout",
    LOADING_NOTE: "Loading note...",
  },

  sr: {
    EMAIL: "Email",
    PASSWORD: "Lozinka",

    LOGIN_TITLE: "Dobrodošao nazad",
    LOGIN_SUBTITLE: "Prijavi se da nastaviš",
    LOGIN_EMAIL_PLACEHOLDER: "Email",
    LOGIN_PASSWORD_PLACEHOLDER: "Lozinka",
    LOGIN_REMEMBER_ME: "Zapamti me",
    LOGIN_SUBMIT: "Prijavi se",
    LOGIN_TO_REGISTER: "Nemaš nalog? Registruj se ovde.",
    LOGIN_MISSING_INFO_TITLE: "Nedostaju podaci",
    LOGIN_MISSING_INFO_MESSAGE: "Unesi email i lozinku.",
    LOGIN_INVALID_EMAIL_TITLE: "Neispravan email",
    LOGIN_INVALID_EMAIL_MESSAGE: "Unesi email u formatu example@email.com.",
    LOGIN_INVALID_PASSWORD_TITLE: "Neispravna lozinka",
    LOGIN_INVALID_PASSWORD_MESSAGE: "Lozinka mora imati najmanje 6 karaktera.",
    LOGIN_FAILED_TITLE: "Prijava neuspešna",
    LOGIN_FAILED_MESSAGE: "Pokušaj ponovo.",

    REGISTER_TITLE: "Kreiraj nalog",
    REGISTER_SUBTITLE: "Registruj se da počneš sa pisanjem beleški",
    REGISTER_EMAIL_PLACEHOLDER: "Email",
    REGISTER_PASSWORD_PLACEHOLDER: "Lozinka",
    REGISTER_SUBMIT: "Registruj se",
    REGISTER_TO_LOGIN: "Već imaš nalog? Prijavi se ovde.",
    REGISTER_MISSING_INFO_TITLE: "Nedostaju podaci",
    REGISTER_MISSING_INFO_MESSAGE: "Unesi email i lozinku.",
    REGISTER_INVALID_EMAIL_TITLE: "Neispravan email",
    REGISTER_INVALID_EMAIL_MESSAGE: "Unesi email u formatu example@email.com.",
    REGISTER_INVALID_PASSWORD_TITLE: "Neispravna lozinka",
    REGISTER_INVALID_PASSWORD_MESSAGE: "Lozinka mora imati najmanje 6 karaktera.",
    REGISTER_SUCCESS_TITLE: "Uspeh",
    REGISTER_SUCCESS_MESSAGE: "Nalog je uspešno kreiran.",
    REGISTER_FAILED_TITLE: "Registracija neuspešna",

    AUTH_INVALID_EMAIL: "Neispravna email adresa.",
    AUTH_INVALID_CREDENTIALS: "Pogrešan email ili lozinka.",
    AUTH_TOO_MANY_REQUESTS: "Previše pokušaja. Pokušaj ponovo za nekoliko minuta.",
    AUTH_NETWORK_FAILED: "Nema internet konekcije. Proveri mrežu i pokušaj ponovo.",
    AUTH_LOGIN_DEFAULT: "Prijava neuspešna. Pokušaj ponovo.",
    AUTH_EMAIL_IN_USE: "Ovaj email je već registrovan.",
    AUTH_WEAK_PASSWORD: "Lozinka je previše slaba. Koristi najmanje 6 karaktera.",
    AUTH_REGISTER_DEFAULT: "Registracija neuspešna. Pokušaj ponovo.",

    NOTE_EDIT_TITLE: "Izmeni belešku",
    NOTE_CREATE_TITLE: "Kreiraj belešku",
    NOTE_TITLE_LABEL: "Naslov",
    NOTE_TITLE_PLACEHOLDER: "Naslov",
    NOTE_CONTENT_LABEL: "Sadržaj",
    NOTE_CONTENT_PLACEHOLDER: "Napiši belešku...",
    NOTE_TAGS_LABEL: "Tagovi",
    NOTE_TAGS_PLACEHOLDER: "projekat, ispit, domaći",
    NOTE_PIN_LABEL: "Zakači na vrh",
    NOTE_COLOR_LABEL: "Boja",
    NOTE_REMINDER_LABEL: "Podsetnik",
    NOTE_UPDATE_BUTTON: "Ažuriraj belešku",
    NOTE_SAVE_BUTTON: "Sačuvaj belešku",
    NOTE_NOT_FOUND_TITLE: "Beleška nije pronađena",
    NOTE_NOT_FOUND_MESSAGE: "Nije moguće učitati traženu belešku.",
    NOTE_LOAD_FAILED_TITLE: "Greška",
    NOTE_LOAD_FAILED_MESSAGE: "Nije moguće učitati belešku. Pokušaj ponovo.",
    NOTE_MISSING_INFO_TITLE: "Nedostaju podaci",
    NOTE_MISSING_INFO_MESSAGE: "Naslov i sadržaj su obavezni.",
    NOTE_INVALID_TITLE_TITLE: "Neispravan naslov",
    NOTE_INVALID_TITLE_SHORT: "Naslov mora imati najmanje 3 karaktera.",
    NOTE_INVALID_TITLE_LONG: "Naslov može imati najviše 120 karaktera.",
    NOTE_INVALID_CONTENT_TITLE: "Neispravan sadržaj",
    NOTE_INVALID_CONTENT_SHORT: "Sadržaj mora imati najmanje 5 karaktera.",
    NOTE_INVALID_CONTENT_LONG: "Sadržaj može imati najviše 5000 karaktera.",
    NOTE_NOT_SIGNED_IN_TITLE: "Nisi prijavljen",
    NOTE_NOT_SIGNED_IN_MESSAGE: "Prijavi se da sačuvaš belešku.",
    NOTE_SAVE_FAILED_TITLE: "Greška",
    NOTE_SAVE_FAILED_MESSAGE: "Nije moguće sačuvati belešku. Pokušaj ponovo.",
    NOTE_REMINDER_PREVIEW: (dateText) => `Podsetnik zakazan za ${dateText}`,

    HOME_GREETING: (email) => `Zdravo, ${email}`,
    HOME_SEARCH_PLACEHOLDER: "Pretraži beleške",
    HOME_NEW_NOTE_BUTTON: "+ Nova beleška",
    HOME_STATS_TOTAL: "Tvoje beleške",
    HOME_STATS_PINNED: "Zakačene",
    HOME_LIST_EMPTY: "Još nema beleški. Počni kreiranjem!",
    HOME_LIST_CREATE_BUTTON: "Kreiraj belešku",
    HOME_NOTE_DRAFT: "Nacrt",
    HOME_NOTE_UNPIN: "Otkači",
    HOME_NOTE_PIN: "Zakači",
    HOME_NOTE_EDIT: "Izmeni",
    HOME_NOTE_DELETE: "Obriši",
    HOME_FILTER_ALL: "Sve",
    HOME_FILTER_PINNED: "Zakačene",
    HOME_FILTER_RECENT: "Nedavno",
    HOME_SORT_RECENT: "Nedavno",
    HOME_SORT_TITLE: "A-Z",
    HOME_FILTER_COLOR: "Boja",
    HOME_TAB_TITLE: "Početna",
    CREATE_TAB_TITLE: "Kreiraj",
    LOGOUT_TAB_TITLE: "Odjava",
    LOADING_NOTE: "Učitavanje beleške...",
  }
};

